author: Vincenzo Pellegrini
logo: UniGestionale
menu:
    - name: Home
      link: "#top"
    - name: About Us
      link: "#about"
    - name: Guests
      link: "#courses"
    - name: Our team
      link: "#team"
menusocial:
    link: https://instagram.com/ingegneriagestionalepolito?igshid=10bn61kp0zd1o
    icon: fa-instagram
footer:
    mail: info@unigestionale.it
    social:
        - icon: fa-instagram
          link: https://instagram.com/ingegneriagestionalepolito?igshid=10bn61kp0zd1o
        - icon: fa-linkedin
          link: https://www.linkedin.com/company/unigestionale/
        - icon: fa-telegram
          link: https://t.me/joinchat/AAAAAEtu7iUJPGnlCWca8A
